pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
    }

    parameters {

        choice (
            name: 'TF_ACTION',
            choices: ['PLAN', 'APPLY', 'DESTROY'],
            description: 'Choose Action To Perform'
        )
    }

    stages {
        stage ('Terraform Plan') {
        when {
            expression {params.TF_ACTION == 'PLAN'}
        }    
            steps {
                dir ('terraform-infrastructure') {
                sh 'terraform init'
                sh 'terraform fmt'
                sh 'terraform validate'
                sh 'terraform plan'
                }
            }
        }

        stage ('Terraform Apply') {
        when {
            expression {params.TF_ACTION == 'APPLY'}
        }    
            steps {
                dir ('terraform-infrastructure') {
                sh 'terraform init'
                sh 'terraform fmt'
                sh 'terraform validate'
                sh 'terraform apply --auto-approve'
                }
            }
        }

        stage ('Terraform Destroy') {
        when {
            expression {params.TF_ACTION == 'DESTROY'}
        }    
            steps {
                dir ('terraform-infrastructure') {
                sh 'terraform init'
                sh 'terraform fmt'
                sh 'terraform validate'
                sh 'terraform destroy --auto-approve'
                }
            }
        }
    }

    post {
        success {
            echo 'Infrastructure built successfully'
        }
        failure {
            echo 'Infrastructure building failed'
        }
    }
}