pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
    }

    parameters {
        choice(
        name: 'TF_ACTION',
        choices: ['DEPLOY_JAVA_APP', 'DEPLOY_PYTHON_APP', 'DEPLOY_NGINX_WEB_APP'],
        description: 'Select Action To Perform'
      )
    }

    stages {
        stage ('Deploy Web App Nginx') {
        when {
            expression {params.TF_ACTION == 'DEPLOY_NGINX_WEB_APP'}
        }
            steps {
                 sshagent (credentials: ['AWS-SSH-KEY']) {
                sh '''
                WEB_INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=web-instance" \
                --query "Reservations[0].Instances[0].PrivateIpAddress" \
                --output text)

                ssh -o StrictHostKeyChecking=no ubuntu@$WEB_INSTANCE_PRIVATE_IP << EOF
                cd ~ 
                sudo apt install unzip -y
                 JAVAVM=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=java-instance" \
                --query "Reservations[0].Instances[0].PublicIpAddress" \
                --output text) 
                
                echo ${JAVAVM}
                scp python_ip.txt ubuntu@$WEB_INSTANCE_PRIVATE_IP:/home/ubuntu/python_ip.txt

                PYTHON_INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=python-instance" \
                --query "Reservations[0].Instances[0].PublicIpAddress" \
                --output text)
                echo "$PYTHON_INSTANCE_PUBLIC_IP"

                sudo apt install nginx -y 
                sudo systemctl daemon-reload 
                sudo systemctl enable nginx 
                sudo systemctl start nginx 
                sudo rm -rf fruits-veg_market 
                cd ~
                git clone https://github.com/techbleat/fruits-veg_market.git 
                cd ~/fruits-veg_market/web 
                 sudo cp ~/fruits-veg_market/web/index.html /var/www/html/index.html
                '''
                 }
            }
        }

        stage ('Deploy Java App') {
        when {
            expression {params.TF_ACTION == 'DEPLOY_JAVA_APP'}
        }
            steps {
                 sshagent (credentials: ['AWS-SSH-KEY']) {
                sh '''
                JAVA_INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=java-instance" \
                --query "Reservations[0].Instances[0].PublicIpAddress" \
                --output text) 

                scp $WORKSPACE/jenkins-files/deployments/vegetables.service  ubuntu@$JAVA_INSTANCE_PUBLIC_IP:/tmp
                

                ssh -o StrictHostKeyChecking=no ubuntu@$JAVA_INSTANCE_PUBLIC_IP << EOF
                cd ~
                sudo rm -rf fruits-veg_market
                git clone https://github.com/techbleat/fruits-veg_market.git
                sudo cp /tmp/vegetables.service /etc/systemd/system/vegetables.service
                sudo systemctl daemon-reload
                sudo systemctl enable vegetables.service
                sudo systemctl start vegetables.service
                '''
                 }
            }

        }

        stage ('Deploy Python App') {
        when {
            expression {params.TF_ACTION == 'DEPLOY_PYTHON_APP'}
        }
            steps {
                 sshagent (credentials: ['AWS-SSH-KEY']) {
                sh '''
                 PYTHON_INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=python-instance" \
                --query "Reservations[0].Instances[0].PrivateIpAddress" \
                --output text)

                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/fruits.service ubuntu@$PYTHON_INSTANCE_PUBLIC_IP:/tmp

                ssh -o StrictHostKeyChecking=no ubuntu@$PYTHON_INSTANCE_PUBLIC_IP << EOF
                sudo cp /tmp/fruits.service /etc/systemd/system/fruits.service
                cd ~ 
                sudo rm -rf fruits-veg_market 
                git clone https://github.com/techbleat/fruits-veg_market.git 
                cd ~/fruits-veg_market/python
                python3 -m venv .venv
                source .venv/bin/activate
                python -m pip install -r requirements.txt
                sudo systemctl daemon-reload 
                sudo systemctl enable fruits.service 
                sudo systemctl start fruits.service 
                '''
                 }
            }

        }
    }

    post {
        success {
            echo 'App deployed successfully'
        }

        failure {
            echo 'App deployment failed'
        }
    }


}