pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
    }

    parameters {
        choice(
        name: 'TF_ACTION',
        choices: ['WEB_AMI', 'JAVA_AMI', 'PYTHON_AMI'],
        description: 'Select AMI To Create'
    )

    }

    // This stage builds the nginx web server AMI using Packer 
    stages {
        stage ('Create Web AMI') {
        when {
            expression {params.TF_ACTION == 'WEB_AMI'}
        }
            steps {
                dir ('packer-ami') {
                 sh 'ls -ltr'
                 sh 'packer init .'
                 sh 'packer fmt .'
                 sh 'packer validate .'
                 sh 'packer build nginx-web.pkr.hcl'
                }
            }

        }

        // This stage builds the java app AMI using Packer 

        stage ('Create Java AMI') {
        when {
            expression {params.TF_ACTION == 'JAVA_AMI'}
        }
            steps {
                dir ('packer-ami') {
                 sh 'ls -ltr'
                 sh 'packer init .'
                 sh 'packer fmt .'
                 sh 'packer validate .'
                 sh 'packer build java.pkr.hcl'
               }
            }
        }

        // This stage builds the python app AMI using Packer 
        stage ('Create Python AMI') {
        when {
            expression {params.TF_ACTION == 'PYTHON_AMI'}
        }
            steps {
                dir ('packer-ami') {
                 sh 'ls -ltr'
                 sh 'packer init .'
                 sh 'packer fmt .'
                 sh 'packer validate .'
                 sh 'packer build python.pkr.hcl'
                }
            }

        }

    }

    post {
        success {
            echo 'AMI built successfully'
        }

        failure {
            echo 'AMI  failed'
        }
    }


}