pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
    }

    parameters {
        choice(
        name: 'PACKER_AMI',
        choices: ['WEB_AMI', 'JAVA_AMI', 'PYTHON_APP'],
        description: 'Select AMI To Create'
    )

    }

    stages {
        stage ('Create Web AMI') {
        when {
            expression {params.TF_ACTION == 'WEB_AMI'}
        }
            steps {
                 sh 'ls -ltr'
                 sh 'packer fmt .'
                 sh 'packer validate .'
                 sh 'packer build web.pkr.hcl'
            }

        }

        stage ('Create Java AMI') {
        when {
            expression {params.TF_ACTION == 'JAVA_AMI'}
        }
            steps {
                 sh 'ls -ltr'
                 sh 'packer fmt .'
                 sh 'packer validate .'
                 sh 'packer build java.pkr.hcl'
            }

        }

        stage ('Create Python AMI') {
        when {
            expression {params.TF_ACTION == 'PYTHON_AMI'}
        }
            steps {
                 sh 'ls -ltr'
                 sh 'packer fmt .'
                 sh 'packer validate .'
                 sh 'packer build python.pkr.hcl'
            }

        }

    }

    post {
        success {
            echo 'AMI built successfully'
        }

        failure {
            echo 'AMI  failed'
        }
    }


}